### ISSUE TITLE
Zastąpienie System.out.println poprzez logger

### ISSUE THREAD

**Issue by kaniad99** [kania-garbacz/Euclidean-TSP#1]
Należy przerobić wyświetlanie wyników na ekran przy pomocy loggera. Może to być log4j albo dowolne inne narzędzie.

DoD: SonalLint nie wyświetla ostrzeżenia o używaniu System.out

![image](https://user-images.githubusercontent.com/18015544/207338341-3b1da7c8-c674-48d9-a110-8cb767de4912.png)

**Comment by b-garbacz** [comment]
This functionality prevents the Hamiltonian cycle from being printed.
